[ric3]
version = "1.6.0"

[dut]
files = ["rvfi_pc_bwd_check.sv", "picorv32.sv", "wrapper.sv", "tb.sv"]
include_files = ["defines.sv", "rvfi_macros.vh"]
reset = "reset"
top = "testbench"

[modeling]
parser = "yosys_slang"
