[ric3]
version = "1.6.0"

[dut]
files = [
    "rtl/serv_bufreg.v",
    "rtl/serv_bufreg2.v",
    "rtl/serv_alu.v",
    "rtl/serv_csr.v",
    "rtl/serv_ctrl.v",
    "rtl/serv_decode.v",
    "rtl/serv_immdec.v",
    "rtl/serv_mem_if.v",
    "rtl/serv_rf_if.v",
    "rtl/serv_rf_ram.v",
    "rtl/serv_rf_ram_if.v",
    "rtl/serv_state.v",
    "rtl/serv_debug.v",
    "rtl/serv_top.v",
    "rtl/serv_rf_top.v",
    "rvfi_causal_check.sv",
    "wrapper.sv",
    "tb.sv",
]
include_files = ["defines.sv", "rvfi_macros.vh"]
reset = "reset"
top = "testbench"

[modeling]
parser = "yosys_slang"
